### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NelisW/pyradi#13]
```
What steps will reproduce the problem?
1. I used SVN to download PyRadi and install to my Canopy Site-Packages 
Directory.
2. When I import Pyradi to use I get error message:

import pyradi as pyradi
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-1901b7ea3e08> in <module>()
----> 1 import pyradi as pyradi

C:\Users\fitzgetm\AppData\Local\Enthought\Canopy32\User\lib\site-packages\pyradi
\__init__.py in <module>()
     37 
     38 import rychroma
---> 39 import ryplanck
     40 import ryfiles
     41 import ryplot

C:\Users\fitzgetm\AppData\Local\Enthought\Canopy32\User\lib\site-packages\pyradi
\ryplanck.py in <module>()
     49 import numpy
     50 import scipy.constants as const
---> 51 import pyradi.ryutils as ryutils
     52 
     53 

AttributeError: 'module' object has no attribute 'ryutils'

What is the expected output? What do you see instead?
I expect to properly load module. INstead I get the above error message

What version of the product are you using? On what operating system?
PyRadi 115, Python 2.7.3, Numpy 1.7.1, Scipy 0.12, Mayavi $.3, Windows 8

Please provide any additional information below.

```

Original issue reported on code.google.com by `tomfitzr...@gmail.com` on 27 Aug 2013 at 1:29

**Comment by NelisW** [comment]
Hi there

I removed pyradi from PyPI, to became quite a burden to maintain and there
are very few installs from there.

Please use the GitHub repo, which is the only and definitive version of
pyradi.
https://github.com/NelisW/pyradi
If you clone or download you can use the code from the cloned/downloaded
folder if you put a pyradi.pth file in your site-packages folder. The
filename must be the name of the package (pyradi) with the pth extension
(for path).  With this file in site-packages, Python will know where to
load it from.

here is where it is in Anaconda on my PC:
[image: image.png]

The contents of this file must be the absolute path to where the pyradi
setup.py or readme file is located on your disk.
In my case the file has only one line:
V:\work\WorkN\pyradi\pyradi

[image: image.png]

If you clone from GitHub, you can always get the latest version by updating
your clone of the repo.
I don't change so often any more, things are quite stable, even though we
use it daily at a number of different sites.

Also see the example notebooks here:
https://github.com/NelisW/ComputationalRadiometry

thanks for your interest!

good luck

Nelis

ps. you can reach me at neliswillers@gmail.com
