### ISSUE TITLE
Modtran 4 or 5 capability

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NelisW/pyradi#2]
```
Modtran 4/5 tape5 read/write function
Modtran execution capability
Modtran tape7 and tape8 read capability
```

Original issue reported on code.google.com by `neliswil...@gmail.com` on 1 Jun 2012 at 8:40

**Comment by NelisW** [comment]
Currently we only read tape7 files created with modtran 4 or 5.
We use proprietary C++ code to write tape5 files, it is quite a nightmare to work through all the options and variations.  Even in the commercial product from Ontar they sometimes make mistakes - and I believe their code has been well tested through years of customer use. So reading/writing tape5 will only be  available if I have much more time (such as after retirement).
